# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CeremaSoComptages
                                 A QGIS plugin
 Gestion de trafics Cerema SO
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-10-17
        copyright            : (C) 2020 by martin Schoreisz
        email                : martin.schoreisz@cerema.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CeremaSoComptages class from file CeremaSoComptages.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ceremaso_comptages import CeremaSoComptages
    return CeremaSoComptages(iface)
