# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CeremaSoComptagesDialog
                                 A QGIS plugin
 Gestion de trafics Cerema SO
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-10-17
        git sha              : $Format:%H$
        copyright            : (C) 2020 by martin Schoreisz
        email                : martin.schoreisz@cerema.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets,QtGui
from qgis.PyQt.QtWidgets import QGroupBox,QCheckBox
from PyQt5.QtCore import pyqtSlot
import ceremaso_comptages.Donnees_individuelles as di

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS_base, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ceremaso_comptages_dialog_base.ui'))

FORM_CLASS_traiterPt, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ceremaso_comptages_dialog_traiter_pt_comptage.ui'))

FORM_CLASS_VisuExport, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ceremaso_comptages_dialog_visu-export.ui'))

class CeremaSoComptagesDialog(QtWidgets.QDialog, FORM_CLASS_base):
    def __init__(self, parent=None):
        """Constructor."""
        super(CeremaSoComptagesDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        #signal/slots
        self.pushButtonTraiterPointComptage.clicked.connect(self.ouvrirTraiterPtDialog)
        
    def ouvrirTraiterPtDialog(self):
        """
        ouvrir la fenetre de la classe CeremaSoComptagesTraiterPtDialog
        """
        self.fenetreTraiterPt=CeremaSoComptagesTraiterPtDialog()
        self.fenetreTraiterPt.show()
        # Run the dialog event loop
        result = self.fenetreTraiterPt.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            print('ok')
        
class CeremaSoComptagesTraiterPtDialog(QtWidgets.QDialog, FORM_CLASS_traiterPt):
    def __init__(self, parent=None):
        """Constructor."""
        super(CeremaSoComptagesTraiterPtDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        #signal/slots
        self.radioButtonTraiterCpt1Fichier.toggled.connect(self.basculerQgisFileWidget)
        self.radioButtonTraiterCpt1point.toggled.connect(self.basculerQgisFileWidget)
        self.radioButtonTraiterCptPlusieursPt.toggled.connect(self.basculerQgisFileWidget)
        self.buttonBox.accepted.connect(self.ouvrirVisuExport)
        
    
    @pyqtSlot()
    def basculerQgisFileWidget(self):
        dicoBoutonChoix={'radioButtonTraiterCpt1Fichier':self.mQgsFileWidgetTraiter1sens,
                        'radioButtonTraiterCpt1point':self.mQgsFileWidgetTraiter1Point,
                        'radioButtonTraiterCptPlusieursPt' : self.mQgsFileWidgetTraiterPlusieursPoints}
        for k, v in dicoBoutonChoix.items() :
            if self.sender().objectName()==k : 
                if not v.isEnabled() :
                    v.setEnabled(True)
                else : 
                    v.setEnabled(False)
    
    @pyqtSlot()
    def ouvrirVisuExport(self):
        """
        recuprere le text du widget qui est allume et ouvre la fenetre suivante
        """
        for t,w in {'fichiers':self.mQgsFileWidgetTraiter1sens, '1Point':self.mQgsFileWidgetTraiter1Point,
                    'plusieursPoints':self.mQgsFileWidgetTraiterPlusieursPoints}.items() : 
            if w.isEnabled() : 
                source=w.splitFilePaths(w.filePath())
                typeTraitement=t
                break
                
        self.fenetreVisuExport=CeremaSoComptagesVisuExport(typeTraitement,source)
        self.fenetreVisuExport.show()
        
class CeremaSoComptagesVisuExport(QtWidgets.QDialog, FORM_CLASS_VisuExport):
    def __init__(self, typeTraite,source,parent=None):
        """Constructor."""
        super(CeremaSoComptagesVisuExport, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.buttonBox.accepted.connect(self.visuGraph)
        self.groupBoxVisu.toggled.connect(self.basculeGroupBox)
        self.groupBoxExport.toggled.connect(self.basculeGroupBox)
        
        self.typeTraite=typeTraite
        self.source=source
        self.cpt=self.calculDfComptage()
        
    def calculDfComptage(self):
        if self.typeTraite=='1Point' :
            cpt=di.ComptageDonneesIndiv(self.source[0])
        return cpt
    
    def trouverCheckBoxOn(self):
        if self.groupBoxVisu.isChecked() : 
            listPeriod=[cb.text().lower().replace(' ','') for cb in self.groupBoxVisuPeriode.findChildren(QCheckBox) if cb.isChecked()]
            listSens=[cb.text().lower().replace(' ','') for cb in self.groupBoxVisuSens.findChildren(QCheckBox) if cb.isChecked()]
            listTypeVeh=[cb.text().lower().replace(' ','') for cb in self.groupBoxTypeVeh.findChildren(QCheckBox) if cb.isChecked()]
        return listPeriod,listSens,listTypeVeh
    
    @pyqtSlot()
    def visuGraph(self):
        listPeriod,listSens,listTypeVeh=self.trouverCheckBoxOn()
        self.cpt.graphs(listTypeVeh, listPeriod, listSens)
        for p in listPeriod :
            for s in listSens :
                print(p, s)
                self.cpt.dicoHoraire[p][s]['graph'].show()
                self.cpt.dicoJournalier[p][s]['graph'].show()
                if s=='2sens' : 
                    self.cpt.dicoJournalier[p]['compSens']['graph'].show()
    
    @pyqtSlot()
    def basculeGroupBox(self):
        if self.sender().isChecked():
            if self.sender().objectName()=='groupBoxVisu' : 
                self.groupBoxExport.setEnabled(False)
            else :
                self.groupBoxVisu.setEnabled(False)
        else :
            if self.sender().objectName()=='groupBoxVisu' : 
                self.groupBoxExport.setEnabled(True)
            else : 
                self.groupBoxVisu.setEnabled(True)
